homepage:
  path: /
  controller: App\Controller\PortfolioController::index

article_add:
  path: /add
  controller: App\Controller\PortfolioController::add

article_show:
  path: /show/{url}
  controller: App\Controller\PortfolioController::show

article_edit:
  path: /edit/{id}
  controller: App\Controller\PortfolioController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /remove/{id}
  controller: App\Controller\PortfolioController::remove
  requirements:
    id: '\d+'