$(function(){
    $("#ladiv").load("./PHP/connnexion.php")
    $("#ladiv2").load("./PHP/inscription.php")
    $("#ladiv").hide()
    $("#ladiv2").hide()
    $("#connect").click(function(){
        $("#ladiv").toggle();
    })
    $("#disconnect").click(function(){
        $("#ladiv2").toggle();
    })
})